extends SceneTree

const FlockRunState = preload("res://scripts/core/reboot/flock_run_state.gd")


func _init() -> void:
	var first = FlockRunState.new_run(424242)
	var second = FlockRunState.new_run(424242)
	assert(first.snapshot() == second.snapshot())
	assert(first.health == 3, "a new flock starts with three health")
	assert(first.score == 0, "a new flock starts with zero score")
	assert(first.combo == 0, "a new flock starts with zero combo")
	assert(first.rescue("goose_greta", "goose"))
	assert(first.rescue("pigeon_pip", "pigeon"))
	assert(not first.rescue("goose_greta", "goose"))
	assert(first.companions.size() == 2)
	assert(first.rescue("duck_dara", "duck"))
	assert(first.rescue("owl_otto", "owl"))
	assert(first.rescue("swan_sue", "swan"))
	assert(not first.rescue("crow_cora", "crow"))
	assert(first.companions.size() == 5)
	first.begin_act("brawl")
	first.record_event("collapse", {"target_id": "antenna_a"})
	assert(first.event_ledger[-1].kind == "collapse")
	var options := first.choice_options()
	assert(options.size() == 3)
	var ledger_before_choice: int = first.event_ledger.size()
	assert(first.apply_choice(str(options[0].id)))
	assert(not first.apply_choice(str(options[0].id)))
	assert(first.event_ledger.size() == ledger_before_choice + 1, "one choice records one build event")
	assert(first.event_ledger[-1].kind == "build_choice", "the build event has a stable kind")
	assert(first.snapshot().health == 3 and first.snapshot().score == 0 and first.snapshot().combo == 0)

	var progressed_first = FlockRunState.new_run(424242)
	var progressed_second = FlockRunState.new_run(424242)
	for state in [progressed_first, progressed_second]:
		assert(state.rescue("goose_greta", "goose"))
		state.begin_act("brawl")
		state.record_event("collapse", {"target_id": "antenna_a"})
	var first_options := progressed_first.choice_options()
	var second_options := progressed_second.choice_options()
	assert(first_options == second_options)
	assert(progressed_first.apply_choice(str(first_options[0].id)))
	assert(progressed_second.apply_choice(str(second_options[0].id)))
	assert(progressed_first.build == progressed_second.build)
	assert(progressed_first.event_ledger == progressed_second.event_ledger)
	assert(progressed_first.snapshot() == progressed_second.snapshot())
	print("PASS flock_run_state_test")
	quit(0)
